<template >
  <div class="main-class">
    <ClientOnly>
      <Header></Header>
    </ClientOnly>
    <slot />
    <Footer></Footer>
    <ClientOnly>
      <TransitinPage></TransitinPage>
    </ClientOnly>
  </div>
</template>

<script>
// import "../node_modules/ant-design-vue/dist/antd.css";
export default {
  data() {
    return {};
  },
  mounted() {},
  methods: {},
};
</script>

<style>
input,
textarea {
  margin: 0;
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}

input {
  overflow: visible;
}
/* This stylesheet generated by Transfonter (https://transfonter.org) on August 23, 2017 4:44 PM */

@font-face {
  font-family: "Segoe UI";
  src: url("/fonts/SegoeUI-Light.eot");
  src: url("/fonts/SegoeUI-Light.eot?#iefix") format("embedded-opentype"),
    url("/fonts/SegoeUI-Light.woff") format("woff"),
    url("/fonts/SegoeUI-Light.ttf") format("truetype");
  font-weight: 300;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("/fonts/SegoeUI-BoldItalic.eot");
  src: url("/fonts/SegoeUI-BoldItalic.eot?#iefix") format("embedded-opentype"),
    url("/fonts/SegoeUI-BoldItalic.woff") format("woff"),
    url("/fonts/SegoeUI-BoldItalic.ttf") format("truetype");
  font-weight: bold;
  font-style: italic;
}

@font-face {
  font-family: "Segoe UI";
  src: url("/fonts/SegoeUI-SemiBold.eot");
  src: url("/fonts/SegoeUI-SemiBold.eot?#iefix") format("embedded-opentype"),
    url("/fonts/SegoeUI-SemiBold.woff") format("woff"),
    url("/fonts/SegoeUI-SemiBold.ttf") format("truetype");
  font-weight: 600;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("/fonts/SegoeUI.eot");
  src: url("/fonts/SegoeUI.eot?#iefix") format("embedded-opentype"),
    url("/fonts/SegoeUI.woff") format("woff"),
    url("/fonts/SegoeUI.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("/fonts/SegoeUI-Bold.eot");
  src: url("/fonts/SegoeUI-Bold.eot?#iefix") format("embedded-opentype"),
    url("/fonts/SegoeUI-Bold.woff") format("woff"),
    url("/fonts/SegoeUI-Bold.ttf") format("truetype");
  font-weight: bold;
  font-style: normal;
}

@font-face {
  font-family: "Segoe UI";
  src: url("/fonts/SegoeUI-Italic.eot");
  src: url("/fonts/SegoeUI-Italic.eot?#iefix") format("embedded-opentype"),
    url("/fonts/SegoeUI-Italic.woff") format("woff"),
    url("/fonts/SegoeUI-Italic.ttf") format("truetype");
  font-weight: normal;
  font-style: italic;
}

@font-face {
  font-family: Playfair Display;
  src: url(/fonts/PlayfairDisplay-Medium.eot);
  src: url(/fonts/PlayfairDisplay-Medium.ttf) format("truetype");
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: "Playfair Display";
  src: url("/fonts/PlayfairDisplay-Regular.ttf") format("truetype");
  font-weight: 300;
  font-style: normal;
}

@font-face {
  font-family: "Playfair Display";
  src: url("/fonts/PlayfairDisplay-BoldItalic.ttf") format("truetype");
  font-weight: bold;
  font-style: italic;
}

@font-face {
  font-family: "Playfair Display";
  src: url("/fonts/PlayfairDisplay-SemiBold.ttf") format("truetype");
  font-weight: 600;
  font-style: normal;
}

@font-face {
  font-family: "Playfair Display";
  src: url("/fonts/PlayfairDisplay-Medium.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "Playfair Display";
  src: url("/fonts/PlayfairDisplay-Bold.ttf") format("truetype");
  font-weight: bold;
  font-style: normal;
}

@font-face {
  font-family: "Playfair Display";
  src: url("/fonts/PlayfairDisplay-Italic.ttf") format("truetype");
  font-weight: normal;
  font-style: italic;
}

.container-fluid {
  margin: auto;
}

.entry-btn {
  border-radius: 2px;
  background: #f15b67;

  width: 280px;
  height: 56px;
  padding: 16px;
  gap: 8px;

  font-family: Segoe UI;
  font-size: 16px;
  font-style: normal;
  font-weight: 600;
  line-height: 26.04px;
  letter-spacing: 3px;
  text-transform: uppercase;
  margin-right: 32px;
  color: white;
  margin-bottom: 16px;
}
.entry-btn a {
  color: white;
}
.gift-btn {
  color: #f15b67;
  text-align: center;
  font-family: Segoe UI;
  font-size: 16px;
  font-style: normal;
  font-weight: 600;
  line-height: 26.04px;
  letter-spacing: 3px;
  text-transform: uppercase;
  border: #f15b67 1px solid;
  border-radius: 2px;
  background: transparent;
  padding: 14px 16px;
  height: 56px;
}

@media (max-width: 1150px) {
  .button-slide_block {
    width: max-content;
  }

  .entry-btn {
    margin-right: 16px;
  }
}

@media (max-width: 1050px) {
  .button-slide_block {
    flex-direction: column;
    display: flex;
    margin: auto;
    position: relative;
    z-index: 4545454;
  }
}

@media (max-width: 768px) {
  .entry-btn {
    width: 100%;
    margin-right: 0;
  }

  .gift-btn {
    color: #f15b67;
    border: none;
    padding: 0;
    border: none !important;
    width: fit-content;
    padding-top: 16px;
    position: relative;
  }

  .gift-btn::before {
    display: none !important;
  }

  .gift-btn::after {
    content: "";
    width: 100%;
    height: 1px;
    background: #f15b67;
    position: absolute;
    bottom: -2px;
    left: 0;
    opacity: 0;
    transition: all 0.3s ease;
  }

  .gift-btn:hover::after {
    content: "";
    opacity: 1;
  }

  .button-slide_block {
    flex-direction: column;
    display: flex;
    margin: auto;
    position: relative;
    z-index: 4545454;
  }

  .gift-btn {
    color: #f15b67;
    border: none;
    padding: 16px 0;
  }

  .gift-btn::after {
    display: none;
  }
}

@media (min-width: 768px) {
  .container-fluid {
    max-width: initial;
    padding-left: 48px !important;
    padding-right: 48px !important;
  }
}

@media (min-width: 1360px) {
  .container-fluid {
    max-width: 1440px;
    padding-left: 112px !important;
    padding-right: 112px !important;
  }
}

@media (max-width: 768px) {
  .container-fluid {
    max-width: initial;
    padding-left: 24.5px !important;
    padding-right: 24.5px !important;
  }
}

.main-class {
  max-width: 100vw;
  overflow: hidden;
}

#app {
  overflow-x: hidden;
}

.ant-image:hover {
  box-shadow: 0 0 30px 0 rgba(var(--ca-dark), 0.3);
}

.ant-image-preview-wrap .anticon {
  display: block;
}

.ant-image {
  cursor: pointer;
}

.ant-carousel .slick-dots li button {
  background: #fff;
  background: transparent;
  border: 0;
  border: 1px solid #fff;
  border-radius: 100%;
  color: transparent;
  cursor: pointer;
  display: block;
  font-size: 0;
  height: 1.5vw;
  opacity: 1;
  outline: none;
  padding: 0;
  transition: all 0.5s;
  width: 1.5vw;
}

.ant-carousel .slick-dots li {
  margin: 0 5px;
  width: auto !important;
}

.ant-carousel .slick-dots li {
  width: auto !important;
}

.ant-carousel .slick-dots li {
  margin: 0 5px;
}

.ant-carousel .slick-dots-bottom {
  bottom: -2vw;
}

.ant-carousel .slick-dots li.slick-active button {
  width: 1.5vw;
}

.swiper-pagination-bullet {
  width: 1.5vw;
}

.ant-carousel .slick-slide {
  text-align: center;
  overflow: hidden;
}

.ant-carousel .slick-arrow.custom-slick-arrow {
  width: 25px;
  height: 25px;
  font-size: 25px;
  color: #fff;
  opacity: 0.3;
  z-index: 1;
}

.ant-carousel .custom-slick-arrow:before {
  display: none;
}

.ant-carousel .custom-slick-arrow:hover {
  opacity: 0.5;
}

.ant-carousel .slick-slide h3 {
  color: #fff;
}

.ant-carousel .slick-prev,
.ant-carousel .slick-next {
  position: absolute;
  top: 50%;
  display: block;
  width: 20px;
  height: 5px;
  margin-top: -10px;
  padding: 0;
  color: white;
  font-size: 32px;
  line-height: 0;
  background: transparent;
  border: 0;
  outline: none;
  cursor: pointer;
  transition: all 0.3s ease;
}

.anticon {
  display: none;
}

.ant-carousel .slick-next {
  right: 20px !important;
}

.ant-carousel .slick-prev:hover,
.ant-carousel .slick-next:hover,
.ant-carousel .slick-prev:focus,
.ant-carousel .slick-next:focus {
  color: white;
  background: transparent;
  outline: none;
  opacity: 0.6;
}

.ant-carousel .slick-next::before {
  display: block;
}

.ant-carousel .slick-prev::before {
  display: block;
  content: "←";
}

button {
  cursor: pointer;
}

.ant-image-preview-img {
  margin-top: 115px;
  margin-bottom: 20px;
}

.ant-image-preview-img-wrapper {
  display: flex;
  justify-content: center;
}

.ant-image-preview-img {
  max-width: 90%;
  object-fit: contain;
}

.ant-image-preview-operations {
  top: 105px;
}

a {
  color: inherit;
}

.ant-carousel .slick-dots li button {
  border: 1px solid #a87e72 !important;
}

.galery-block .ant-carousel .slick-dots-bottom {
  bottom: -1.5vw;
}

.ant-carousel .slick-dots .slick-active button {
  background: #a87e72 !important;
}

.swiper-pagination-bullet {
  border: 1px solid #a87e72 !important;
  background: transparent;
  left: auto !important;
  right: auto !important;
}

.swiper-pagination-bullet-active-main {
  background: #a87e72 !important;
}

.slide-imgs .ant-image {
  width: 100%;
  height: auto;
  margin-right: 16px;
  margin-left: 16px;
}

.ant-carousel .slick-dots li button {
  width: 24px;
  height: 24px;
}

.ant-carousel .slick-dots .slick-active button {
  width: 24px !important;
  height: 24px !important;
}

.swiper-pagination-bullet {
  width: 24px !important;
  height: 24px !important;
}

.pink-hover {
  transition: all 0.3s ease;
}

.pink-hover:hover {
  background: #d9525d;
}

.white-animation {
  position: relative;
  z-index: 2;
  transition: all 0.4s ease-in-out;
}

.white-animation:before {
  content: "";
  position: absolute;
  z-index: -1;
  width: 0;
  height: 100%;
  top: 0;
  left: 0;
  -webkit-transition: width 0.4s ease-in-out;
  -o-transition: width 0.4s ease-in-out;
  transition: width 0.4s ease-in-out;
  background-color: white;
}

.white-animation:focus,
.white-animation:hover {
  border: 1px solid white;
}

.white-animation:focus:before,
.white-animation:hover:before {
  width: 100%;
}

.swiper-pagination-bullet {
  width: 24px !important;
  height: 24px !important;
  min-width: 24px;
}

.swiper-pagination {
  display: flex;
  width: auto !important;
  bottom: -45px !important;
}

.swiper-pagination-bullet {
  transform: none !important;
}

.swiper-pagination-bullet {
  opacity: 1;
}

.swiper-initialized {
  overflow-y: inherit;
}

.swiper-horizontal > .swiper-pagination-bullets .swiper-pagination-bullet,
.swiper-pagination-horizontal.swiper-pagination-bullets
  .swiper-pagination-bullet {
  margin: 0 var(--swiper-pagination-bullet-horizontal-gap, 8px);
}

.ant-image-img {
  object-fit: cover;
}

.ant-image-img {
  height: 288px;
}

@media (max-width: 1050px) {
  .ant-image-img {
    height: 360px;
  }
}

@media (max-width: 768px) {
  .galery-block .ant-carousel .slick-slide img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .slide-imgs .ant-image {
    height: 384px;
    object-fit: cover;
    width: 100%;
  }

  .slide-imgs .ant-image {
    width: 100%;
  }

  .ant-carousel .slick-dots li button {
    width: 16px;
    height: 16px;
  }

  .ant-carousel .slick-dots .slick-active button {
    width: 16px !important;
    height: 16px !important;
  }

  .swiper-pagination-bullet {
    width: 16px !important;
    height: 16px !important;
    min-width: 16px;
  }

  .ant-carousel .slick-dots {
    position: relative;
    bottom: initial;
    margin-top: 0;
    top: 15px;
  }

  .ant-image-img {
    height: 384px;
  }
}

/* Блок на 4 преимущества */

.couple-el {
  display: flex;
  margin-bottom: 56px;
}

.advantage-el {
  display: flex;
  width: 50%;
}
.predominantly .advantage-el {
  width: 50%;
}

.advantage-el_text {
  color: #7b7d80;
  font-family: Segoe UI;
  font-size: 20px;
  font-style: normal;
  font-weight: 400;
  line-height: 120%;
}

.advantage-el {
  margin-right: 51px;
}

.advantage-el_title {
  color: #a87e72;
  font-family: Playfair Display;
  font-size: 24px;
  font-style: normal;
  font-weight: 600;
  line-height: 120%;
  margin-bottom: 16px;
}

.img-block {
  min-width: 104px;
  height: 104px;
  background: rgba(241, 91, 103, 0.15);
  border-radius: 50%;
  margin-right: 16px;
  display: flex;
}

.img-block img {
  margin: auto;
  width: 44px;
}
@media (max-width: 1150px) {
  .predominantly .advantage-el:last-child {
    margin-bottom: 32px;
  }
  .predominantly .advantage-el {
    margin-right: 0;
  }
  .advantage-el,
  .predominantly .advantage-el {
    width: 100%;
  }
}
@media (max-width: 768px) {
  .advantage-block {
    width: auto;
    margin-bottom: 64px;
  }

  .couple-el {
    flex-direction: column;
    margin-bottom: 32px;
  }
  .predominantly .couple-el {
    margin-bottom: 0;
  }

  .advantage-el:nth-child(1) {
    margin-bottom: 32px;
  }

  .advantage-el_text {
    max-width: initial;
  }

  .advantage-el_title {
    font-size: 20px;
    font-style: normal;
    font-weight: 600;
    line-height: 120%;
  }

  .advantage-el_text {
    font-size: 16px;
    font-style: normal;
    font-weight: 400;
    line-height: 130%;
  }

  .img-block {
    width: 72px;
    height: 72px;
    min-width: 72px;
  }

  .img-block img {
    width: 33.231px;
  }
}

/* Хлебные крошки */
.bread-crumbs {
  margin-top: 125px;
  position: absolute;
  z-index: 3;
  color: #7b7d80;
  text-align: center;
  font-family: Segoe UI;
  font-size: 14px;
  font-style: normal;
  font-weight: 400;
  line-height: 120%;
}
.bread-crumbs a:hover {
  color: #7b7d80;
}
/* Главный блок */

.title-el_block {
  color: #42474e;
  text-align: center;
  font-family: Playfair Display;
  font-size: 40px;
  font-style: normal;
  font-weight: 400;
  line-height: 120%;
  margin-bottom: 32px;
}
.baner-el .title-el_block {
  font-size: 52px;
  text-align: left;
}
.baner-el {
  width: 100%;
  padding-top: 143px;
  padding-bottom: 77px;
  z-index: 2;
  position: relative;
  background: linear-gradient(
    270deg,
    rgba(255, 255, 255, 0) 10.95%,
    rgba(255, 255, 255, 0.58) 32.79%,
    #fff 72.98%
  );
}
.baner_section {
  position: relative;
  width: 100%;
  margin-top: 94px;
  overflow: hidden;
}
.baner_section img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  object-position: center top;
  padding-right: 0 !important;
  margin-right: 0;
}
.banner-img {
  position: absolute;
  width: 100%;
}
.desc-el span {
  margin-right: 16px;
  width: 32px;
  height: 32px;
}
.desc-el {
  display: flex;
  align-items: center;
  color: #7b7d80;
  font-size: 24px;
  font-style: normal;
  font-weight: 400;
  line-height: 120%;
}
.gift-btn a {
  color: #f15b67;
}
.button-block {
  margin-top: 24px;
}
.promotion-slide {
  display: flex;
  background: linear-gradient(
    76deg,
    rgba(250, 191, 191, 0) 0%,
    #fddbdb 30.85%,
    #fff6f6 74.35%,
    rgba(255, 246, 246, 0) 100%
  );
  padding: 8px 0;
  margin: 24px 0;
  align-items: center;
  width: fit-content;
}
.promotion-text {
  color: #42474e;
  font-family: Segoe UI;
  font-size: 36px;
  font-style: normal;
  font-weight: 400;
  line-height: 130%;
  letter-spacing: -0.36px;
  text-transform: uppercase;
  margin-right: 8px;
}

.promotion-percent {
  color: #42474e;
  font-family: Segoe UI;
  font-size: 48px;
  font-style: normal;
  font-weight: 600;
  line-height: 130%;
  letter-spacing: -0.48px;
  margin-right: 24px;
}

.promotion-text_desc {
  color: #42474e;
  font-family: Segoe UI;
  font-size: 28px;
  font-style: normal;
  font-weight: 400;
  line-height: 110%;
  letter-spacing: -0.28px;
}
@media (max-width: 1150px) {
  .baner-el .title-el_block {
    text-align: center;
  }
  .button-block {
    display: flex;
    justify-content: center;
  }
  .baner_section {
    margin-top: 70px;
    aspect-ratio: 1/0.85;
  }
  .baner_section img {
    position: absolute;
    height: 180%;
    object-fit: cover;
    object-position: right -455px;
    padding: 0 !important;
  }
  .baner-el {
    background: linear-gradient(
      1deg,
      #fff 42.58%,
      rgba(255, 255, 255, 0.58) 63.16%,
      rgba(255, 255, 255, 0) 78.08%
    );
    width: 100%;
    position: absolute;
    bottom: 0;
    margin-right: 0;
    padding-top: 190px;
  }
  .bread-crumbs {
    color: #ffffff;
  }
  .banner-img {
    height: 100%;
  }
}
@media (max-width: 1050px) {
  .promotion-slide {
    justify-content: center;
    margin: 24px auto;
  }
}
@media (max-width: 768px) {
  .promotion-text {
    font-size: 20px;
  }

  .promotion-percent {
    font-size: 32px;
  }

  .promotion-text_desc {
    font-size: 16px;
  }
  .promotion-slide {
    justify-content: center;
  }
  .desc-els {
    display: none;
  }
  .baner-el .title-el_block {
    font-size: 24px;
    font-style: normal;
    font-weight: 400;
    line-height: 130%;
  }
  .button-block {
    flex-direction: column;
    align-items: center;
  }
  .baner_section {
    height: calc(100vh);
  }
  .baner_section {
    aspect-ratio: initial;
  }
  .baner_section img {
    height: 169vw;
    object-position: 95% -155px;
  }
  .baner_section {
    height: calc(100vh - 64px);
    margin-top: 64px;
  }
  .baner-el {
    padding-top: 310px;
    padding-bottom: 24px;
    background: linear-gradient(
      180deg,
      rgba(255, 255, 255, 0) 21.39%,
      rgba(255, 255, 255, 0.5) 48.62%,
      #fff 78.51%
    );
  }
  .title-el_block {
    font-size: 22px;
  }
}
@media (max-width: 530px) {
  .baner_section img {
    object-position: 95% 0px;
  }
}
@media (max-width: 400px) {
  .baner_section img {
    object-position: 90% 0px;
    height: 200vw;
  }
}
/* Xenon */

.xenon-therapy_section,
.xenon-plus_section,
.xenon-balance_block,
.predominantly,
.price-table,
.section-block {
  padding-top: 64px;
  padding-bottom: 64px;
}
.xenon-therapy_section .desc-el {
  text-align: center;
  margin-top: 0;
  margin-bottom: 8px;
  color: #7b7d80;
  font-family: Segoe UI;
  font-size: 24px;
  font-style: normal;
  font-weight: 400;
  line-height: 120%;
  text-align: left;
}
.xenon-therapy_section .xenon-therapy_els {
  display: flex;
  margin-top: 64px;
}
.xenon-plus_section .entry-btn {
  margin: auto;
  display: block;
}
@media (max-width: 1150px) {
  .xenon-therapy .advantage-el {
    min-width: 321px;
    width: auto;
    max-width: 430px;
  }
  .xenon-therapy_els {
    flex-wrap: wrap;
  }
  .xenon-therapy_section .xenon-therapy_els {
    justify-content: center;
  }
}
@media (max-width: 1150px) {
  .xenon-therapy .advantage-el {
    min-width: initial;
    width: 321px;
    max-width: initial;
  }
}

@media (max-width: 865px) {
  .xenon-therapy .advantage-el {
    min-width: initial;
    width: 274px;
    max-width: initial;
  }
}
@media (max-width: 768px) {
  .desc-el {
    font-size: 16px;
  }
  .xenon-therapy .desc-el {
    font-size: 20px;
  }
  .xenon-therapy_section .xenon-therapy_els {
    flex-direction: column;
  }
  .xenon-therapy_els .advantage-el_text {
    font-size: 18px;
  }
  .xenon-therapy .advantage-el {
    display: block;
  }
}

/* Факты */
.plus-block .el {
  display: flex;
  background: #fff3d4;
}
.xenon-balance_block {
  display: flex;
  flex-direction: row-reverse;
}
.plus-block img {
  height: auto;
  width: 50%;
  object-fit: cover;
}
.el_block {
  width: 50%;
  display: flex;
}
.text-el_block {
  height: auto;
  background: white;
  margin: 40px;
  padding: 32px;
  width: 100%;
}
.title {
  color: #a87e72;
  font-family: Playfair Display;
  font-size: 32px;
  font-style: normal;
  font-weight: 400;
  line-height: 130%;
  margin-bottom: 0;
}
.strip-el {
  height: 1px;
  width: 100%;
  background: #a87e72;
  margin: 24px 0;
}
.list-el {
  display: flex;
  align-items: center;
  margin-bottom: 16px;
}
.list-el:last-child {
  margin-bottom: 0;
}
.list-el span {
  margin-right: 8px;
}
.plus-block .el:nth-child(2) {
  flex-direction: row-reverse;
  background: #fabfbf;
}
.plus-block {
  margin-bottom: 32px;
}
.plus-block .entry-btn {
  position: relative;
  margin: auto;
  display: block;
}
@media (max-width: 1150px) {
  .xenon-balance_block {
    display: flex;
    flex-direction: column-reverse;
  }
  .advantage-el_text {
    max-width: 100%;
  }
}
@media (max-width: 930px) {
  .plus-block .el {
    flex-direction: column;
  }
  .el_block {
    width: 100%;
  }
  .plus-block img {
    height: 487px;
    width: 100%;
  }
  .plus-block .el:nth-child(2) {
    flex-direction: column;
  }
}
@media (max-width: 768px) {
  .title {
    font-size: 20px;
  }
}

/* xenon balance */
.xenon-balance_section .title-el_block {
  margin-bottom: 40px;
}
.advantage-el {
  margin-bottom: 32px;
}
.xenon-balance_block img {
  object-fit: cover;
}
.advantage-el:last-child {
  margin-bottom: 0;
}
@media (max-width: 1150px) {
  .xenon-balance_section .advantage-el:last-child {
    margin-bottom: 32px;
  }
}
@media (max-width: 768px) {
  .xenon-balance_section .title-el_block {
    margin-bottom: 32px;
  }
  .advantage-el_text {
    font-size: 18px;
  }
  .xenon-therapy_els .advantage-el_text {
    font-size: 16px;
  }

  .xenon-balance_block img {
    aspect-ratio: 1/1;
  }
  .img-container,
  .xenon-therapy .advantage-el {
    width: 100%;
  }
}

/* predominantly  */
.predominantly .img-block {
  line-height: 65px;
}
.img-block {
  font-family: Playfair Display;
  font-size: 60px;
  display: flex;
  align-items: flex-start;
  justify-content: center;
  color: #f15b67;
  line-height: initial;
}
.predominantly .title-el_block {
  margin-bottom: 32px;
}
.couple-el:last-child {
  margin-bottom: 0;
}
@media (max-width: 1150px) {
  .couple-el {
    flex-direction: column;
    margin-bottom: 0;
  }
}
@media (max-width: 768px) {
  .xenon-balance_section .img-block {
    font-size: 45px;
    min-width: 40px;
    width: 40px;
    height: 40px;
  }
  .img-block {
    font-size: 45px;
  }
  .xenon-therapy_section .img-block {
    width: 80px;
    height: 80px;
    margin-bottom: 16px;
    margin-right: 0;
  }
  .xenon-balance_section .img-block img {
    width: 23.231px;
  }
  .advantage-el_title {
    font-size: 24px;
    font-style: normal;
    font-weight: 600;
    line-height: 120%;
  }
  .xenon-therapy_els .advantage-el_text {
    font-size: 18px;
    font-style: normal;
    font-weight: 400;
    line-height: 150%;
  }
  .xenon-therapy .advantage-el {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    margin-right: 0;
  }
  .img-container {
    width: fit-content;
  }
  .xenon-balance_section {
    padding-top: 32px;
  }
  .xenon-balance_block {
    padding-top: 16px;
  }
  .couple-el {
    margin-bottom: 32px;
  }
  .couple-el:last-child {
    margin-bottom: 0;
  }
  .advantage-block {
    margin-bottom: 0;
  }
}

/* pricetable */

.pink-block {
  background: #fef8f5;
}
.price-table .title-el_block {
  margin-bottom: 32px;
}

/* rf-balance */
.rf-balance {
  display: flex;
}
.rf-balance .balance-text,
.rf-balance img {
  width: 50%;
}
.rf-balance .balance-text {
  margin-right: 32px;
}
.rf-balance img {
  object-fit: cover;
  object-position: center right;
}
.rf-balance .desc-el {
  font-size: 18px;
  font-style: normal;
  font-weight: 400;
  line-height: 150%;
  margin-bottom: 32px;
}
.rf-balance .title-el_block {
  text-align: left;
}
@media (max-width: 1150px) {
  .title-el_block {
    text-align: center;
  }
  .rf-balance {
    flex-direction: column;
  }
  .rf-balance .balance-text,
  .rf-balance img {
    width: 100%;
  }
  .rf-balance img {
    height: 480px;
  }
  .rf-balance .balance-text {
    margin-right: 0;
  }
  .rf-balance .entry-btn {
    margin: 32px auto;
  }
  .entry-bnt_block {
    display: flex;
  }
  .rf-balance .specialists-title {
    text-align: center;
  }
}
@media (max-width: 768px) {
  .rf-balance img {
    height: auto;
    aspect-ratio: 1/0.815;
  }
  .rf-balance .desc-el {
    font-size: 16px;
    font-style: normal;
    font-weight: 400;
    line-height: 130%;
  }
  .bread-crumbs {
    display: none;
  }
}
</style>